/**
 * SerialCommUnity (Serial Communication for Unity)
 * Author: Daniel Wilches <dwilches@gmail.com>
 *
 * This work is released under the Creative Commons Attributions license.
 * https://creativecommons.org/licenses/by/2.0/
 */

using UnityEngine;
using System.Collections;
using System.Linq;

/**
 * Sample for reading using polling by yourself, and writing too.
 */
public class SampleUserPolling_ReadWrite : MonoBehaviour
{
    public SerialController serialController;
    string messageIN;
    string messageOUT;

    // Initialization
    void Start()
    {
        serialController = GameObject.Find("SerialController").GetComponent<SerialController>();
    }

    // Executed each frame
    void Update()
    {
        //---------------------------------------------------------------------
        // Receive data
        //---------------------------------------------------------------------

        messageIN = serialController.ReadSerialMessage();

        if (messageIN == null)
            return;

        // Check if the message is plain data or a connect/disconnect event.
        if (ReferenceEquals(messageIN, SerialController.SERIAL_DEVICE_CONNECTED))
            Debug.Log("Connection established");
        else if (ReferenceEquals(messageIN, SerialController.SERIAL_DEVICE_DISCONNECTED))
            Debug.Log("Connection attempt failed or disconnection detected");
        else
            Debug.Log("Message arrived: " + messageIN);

        //---------------------------------------------------------------------
        // Send data
        //---------------------------------------------------------------------
        messageOUT = messageIN;
        serialController.SendSerialMessage(messageOUT);

    }

    public void setMessageOUT(string data)
    {
        messageOUT = data;
    }

    public bool[] getMessageIN()
    {
        return messageIN.Select(x => x == '1').ToArray();
    }
}
